#!/usr/bin/env php
<?php
if( php_sapi_name() !== 'cli' ) {
    die("Meant to be run from command line" . PHP_EOL);
}

define( 'TR_PATH', __DIR__ );
define( 'TR_APP_NAMESPACE', 'App' );

require __DIR__ . '/vendor/autoload.php';

new \TypeRocket\Console\Launcher;